// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gateway.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bs.Gateway {

  /// <summary>Holder for reflection information generated from gateway.proto</summary>
  public static partial class GatewayReflection {

    #region Descriptor
    /// <summary>File descriptor for gateway.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GatewayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1nYXRld2F5LnByb3RvEgpicy5nYXRld2F5IkcKCFB1bHNlUmVxEhAKCG15",
            "X3NwZWVkGAEgASgNEhIKCnNwZWVkX2RhdGEYAiABKA0SFQoNYXR0YWNoZWRf",
            "ZGF0YRgDIAEoDCJHCghQdWxzZVJzcBISCgpzcGVlZF9kYXRhGAEgASgNEhQK",
            "DGF0dGFjaGRfZGF0YRgCIAEoDBIRCgl0aW1lc3RhbXAYAyABKAMirwEKD1Ry",
            "YW5zZmVyRGF0YVJlcRIUCgxkZXN0X2FwcHR5cGUYASABKA0SEgoKZGVzdF9h",
            "cHBpZBgCIAEoDRITCgttYWluX2NtZF9pZBgDIAEoDRISCgpzdWJfY21kX2lk",
            "GAQgASgNEgwKBGRhdGEYBSABKAwSFAoMY2xpZW50X2lwX3Y0GAYgASgNEhQK",
            "DGdhdGVfY29ubl9pZBgHIAEoBBIPCgd1c2VyX2lkGAggASgEIjEKD1RyYW5z",
            "ZmVyRGF0YVJzcBIOCgZyZXN1bHQYASABKA0SDgoGcmVxX2lkGAYgASgNIqEB",
            "CghBdXRoSW5mbxIPCgd1c2VyX2lkGAEgASgEEhQKDGdhdGVfY29ubl9pZBgC",
            "IAEoBBIOCgZyZXN1bHQYAyABKA0SDAoEaW5mbxgEIAEoCRIsCgdvcF90eXBl",
            "GAUgASgOMhsuYnMuZ2F0ZXdheS5BdXRoSW5mby5PcFR5cGUiIgoGT3BUeXBl",
            "EggKBEJpbmQQABIOCgpEaXNjb25uZWN0EAEitAEKCEhlbGxvUmVxEg0KBWFk",
            "X2lkGAIgASgNEg4KBm90aGVycxgDIAEoCRISCgpidWlsZGVyX25vGAQgASgN",
            "EhEKCWdhbWVfa2luZBgFIAEoDRIWCg5jbGllbnRfdmVyc2lvbhgGIAEoCRIT",
            "CgtjbGllbnRfdHlwZRgHIAEoDRISCgpwdWJsaWNfa2V5GAggASgJEhMKC2Vu",
            "Y3J5cHRfa2V5GAkgASgJEgwKBGd1aWQYCiABKAki9AEKCEhlbGxvUnNwEhAK",
            "CHJzcF9mbGFnGAEgASgNEhQKDGdhdGVfYWRkcmVzcxgCIAMoCRITCgtsb2dp",
            "bl90b2tlbhgEIAEoDRISCgpwdWJsaWNfa2V5GAggASgJEhMKC2VuY3J5cHRf",
            "a2V5GAMgASgJEhYKDnZlcnNpb25fcmVzdWx0GAUgASgNEhAKCGRvd25fdXJs",
            "GAYgASgJEgwKBGd1aWQYByABKAkiSgoHUnNwRmxhZxILCgdVTktOT1dOEAAS",
            "DwoLRW5jcnlwdEluZm8QARIRCg1BZHZpY2VOZXdHYXRlEAISDgoKTG9naW5U",
            "b2tlbhAEKpYBCgpDTURHYXRld2F5EgoKBklETm9uZRAAEg4KCklEUHVsc2VS",
            "ZXEQARIOCgpJRFB1bHNlUnNwEAISFQoRSURUcmFuc2ZlckRhdGFSZXEQAxIV",
            "ChFJRFRyYW5zZmVyRGF0YVJzcBAEEg4KCklEQXV0aEluZm8QBRIOCgpJREhl",
            "bGxvUmVxEAYSDgoKSURIZWxsb1JzcBAHQgpaCC9nYXRld2F5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bs.Gateway.CMDGateway), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.PulseReq), global::Bs.Gateway.PulseReq.Parser, new[]{ "MySpeed", "SpeedData", "AttachedData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.PulseRsp), global::Bs.Gateway.PulseRsp.Parser, new[]{ "SpeedData", "AttachdData", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.TransferDataReq), global::Bs.Gateway.TransferDataReq.Parser, new[]{ "DestApptype", "DestAppid", "MainCmdId", "SubCmdId", "Data", "ClientIpV4", "GateConnId", "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.TransferDataRsp), global::Bs.Gateway.TransferDataRsp.Parser, new[]{ "Result", "ReqId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.AuthInfo), global::Bs.Gateway.AuthInfo.Parser, new[]{ "UserId", "GateConnId", "Result", "Info", "OpType" }, null, new[]{ typeof(global::Bs.Gateway.AuthInfo.Types.OpType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.HelloReq), global::Bs.Gateway.HelloReq.Parser, new[]{ "AdId", "Others", "BuilderNo", "GameKind", "ClientVersion", "ClientType", "PublicKey", "EncryptKey", "Guid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Gateway.HelloRsp), global::Bs.Gateway.HelloRsp.Parser, new[]{ "RspFlag", "GateAddress", "LoginToken", "PublicKey", "EncryptKey", "VersionResult", "DownUrl", "Guid" }, null, new[]{ typeof(global::Bs.Gateway.HelloRsp.Types.RspFlag) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CMDGateway {
    [pbr::OriginalName("IDNone")] Idnone = 0,
    /// <summary>
    ///测速请求
    /// </summary>
    [pbr::OriginalName("IDPulseReq")] IdpulseReq = 1,
    /// <summary>
    ///测速回复
    /// </summary>
    [pbr::OriginalName("IDPulseRsp")] IdpulseRsp = 2,
    /// <summary>
    ///数据转发请求
    /// </summary>
    [pbr::OriginalName("IDTransferDataReq")] IdtransferDataReq = 3,
    /// <summary>
    ///数据转发回复
    /// </summary>
    [pbr::OriginalName("IDTransferDataRsp")] IdtransferDataRsp = 4,
    /// <summary>
    ///认证信息
    /// </summary>
    [pbr::OriginalName("IDAuthInfo")] IdauthInfo = 5,
    /// <summary>
    ///握手请求
    /// </summary>
    [pbr::OriginalName("IDHelloReq")] IdhelloReq = 6,
    /// <summary>
    ///握手回复
    /// </summary>
    [pbr::OriginalName("IDHelloRsp")] IdhelloRsp = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  ///测速请求
  /// </summary>
  public sealed partial class PulseReq : pb::IMessage<PulseReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PulseReq> _parser = new pb::MessageParser<PulseReq>(() => new PulseReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PulseReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseReq(PulseReq other) : this() {
      mySpeed_ = other.mySpeed_;
      speedData_ = other.speedData_;
      attachedData_ = other.attachedData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseReq Clone() {
      return new PulseReq(this);
    }

    /// <summary>Field number for the "my_speed" field.</summary>
    public const int MySpeedFieldNumber = 1;
    private uint mySpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MySpeed {
      get { return mySpeed_; }
      set {
        mySpeed_ = value;
      }
    }

    /// <summary>Field number for the "speed_data" field.</summary>
    public const int SpeedDataFieldNumber = 2;
    private uint speedData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SpeedData {
      get { return speedData_; }
      set {
        speedData_ = value;
      }
    }

    /// <summary>Field number for the "attached_data" field.</summary>
    public const int AttachedDataFieldNumber = 3;
    private pb::ByteString attachedData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString AttachedData {
      get { return attachedData_; }
      set {
        attachedData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PulseReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PulseReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MySpeed != other.MySpeed) return false;
      if (SpeedData != other.SpeedData) return false;
      if (AttachedData != other.AttachedData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MySpeed != 0) hash ^= MySpeed.GetHashCode();
      if (SpeedData != 0) hash ^= SpeedData.GetHashCode();
      if (AttachedData.Length != 0) hash ^= AttachedData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MySpeed != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MySpeed);
      }
      if (SpeedData != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SpeedData);
      }
      if (AttachedData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(AttachedData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MySpeed != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MySpeed);
      }
      if (SpeedData != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SpeedData);
      }
      if (AttachedData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(AttachedData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MySpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MySpeed);
      }
      if (SpeedData != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpeedData);
      }
      if (AttachedData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AttachedData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PulseReq other) {
      if (other == null) {
        return;
      }
      if (other.MySpeed != 0) {
        MySpeed = other.MySpeed;
      }
      if (other.SpeedData != 0) {
        SpeedData = other.SpeedData;
      }
      if (other.AttachedData.Length != 0) {
        AttachedData = other.AttachedData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MySpeed = input.ReadUInt32();
            break;
          }
          case 16: {
            SpeedData = input.ReadUInt32();
            break;
          }
          case 26: {
            AttachedData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MySpeed = input.ReadUInt32();
            break;
          }
          case 16: {
            SpeedData = input.ReadUInt32();
            break;
          }
          case 26: {
            AttachedData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///测速请求
  /// </summary>
  public sealed partial class PulseRsp : pb::IMessage<PulseRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PulseRsp> _parser = new pb::MessageParser<PulseRsp>(() => new PulseRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PulseRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseRsp(PulseRsp other) : this() {
      speedData_ = other.speedData_;
      attachdData_ = other.attachdData_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PulseRsp Clone() {
      return new PulseRsp(this);
    }

    /// <summary>Field number for the "speed_data" field.</summary>
    public const int SpeedDataFieldNumber = 1;
    private uint speedData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SpeedData {
      get { return speedData_; }
      set {
        speedData_ = value;
      }
    }

    /// <summary>Field number for the "attachd_data" field.</summary>
    public const int AttachdDataFieldNumber = 2;
    private pb::ByteString attachdData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString AttachdData {
      get { return attachdData_; }
      set {
        attachdData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PulseRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PulseRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpeedData != other.SpeedData) return false;
      if (AttachdData != other.AttachdData) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpeedData != 0) hash ^= SpeedData.GetHashCode();
      if (AttachdData.Length != 0) hash ^= AttachdData.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpeedData != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SpeedData);
      }
      if (AttachdData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(AttachdData);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpeedData != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SpeedData);
      }
      if (AttachdData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(AttachdData);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpeedData != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpeedData);
      }
      if (AttachdData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AttachdData);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PulseRsp other) {
      if (other == null) {
        return;
      }
      if (other.SpeedData != 0) {
        SpeedData = other.SpeedData;
      }
      if (other.AttachdData.Length != 0) {
        AttachdData = other.AttachdData;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpeedData = input.ReadUInt32();
            break;
          }
          case 18: {
            AttachdData = input.ReadBytes();
            break;
          }
          case 24: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpeedData = input.ReadUInt32();
            break;
          }
          case 18: {
            AttachdData = input.ReadBytes();
            break;
          }
          case 24: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///数据转发请求
  /// </summary>
  public sealed partial class TransferDataReq : pb::IMessage<TransferDataReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransferDataReq> _parser = new pb::MessageParser<TransferDataReq>(() => new TransferDataReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransferDataReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataReq(TransferDataReq other) : this() {
      destApptype_ = other.destApptype_;
      destAppid_ = other.destAppid_;
      mainCmdId_ = other.mainCmdId_;
      subCmdId_ = other.subCmdId_;
      data_ = other.data_;
      clientIpV4_ = other.clientIpV4_;
      gateConnId_ = other.gateConnId_;
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataReq Clone() {
      return new TransferDataReq(this);
    }

    /// <summary>Field number for the "dest_apptype" field.</summary>
    public const int DestApptypeFieldNumber = 1;
    private uint destApptype_;
    /// <summary>
    ///目标或源apptype
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DestApptype {
      get { return destApptype_; }
      set {
        destApptype_ = value;
      }
    }

    /// <summary>Field number for the "dest_appid" field.</summary>
    public const int DestAppidFieldNumber = 2;
    private uint destAppid_;
    /// <summary>
    ///目标或源appid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DestAppid {
      get { return destAppid_; }
      set {
        destAppid_ = value;
      }
    }

    /// <summary>Field number for the "main_cmd_id" field.</summary>
    public const int MainCmdIdFieldNumber = 3;
    private uint mainCmdId_;
    /// <summary>
    ///主命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MainCmdId {
      get { return mainCmdId_; }
      set {
        mainCmdId_ = value;
      }
    }

    /// <summary>Field number for the "sub_cmd_id" field.</summary>
    public const int SubCmdIdFieldNumber = 4;
    private uint subCmdId_;
    /// <summary>
    ///次命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SubCmdId {
      get { return subCmdId_; }
      set {
        subCmdId_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    ///转发数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_ip_v4" field.</summary>
    public const int ClientIpV4FieldNumber = 6;
    private uint clientIpV4_;
    /// <summary>
    ///客户端的ip
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ClientIpV4 {
      get { return clientIpV4_; }
      set {
        clientIpV4_ = value;
      }
    }

    /// <summary>Field number for the "gate_conn_id" field.</summary>
    public const int GateConnIdFieldNumber = 7;
    private ulong gateConnId_;
    /// <summary>
    ///gate连接id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong GateConnId {
      get { return gateConnId_; }
      set {
        gateConnId_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 8;
    private ulong userId_;
    /// <summary>
    ///用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransferDataReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransferDataReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DestApptype != other.DestApptype) return false;
      if (DestAppid != other.DestAppid) return false;
      if (MainCmdId != other.MainCmdId) return false;
      if (SubCmdId != other.SubCmdId) return false;
      if (Data != other.Data) return false;
      if (ClientIpV4 != other.ClientIpV4) return false;
      if (GateConnId != other.GateConnId) return false;
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DestApptype != 0) hash ^= DestApptype.GetHashCode();
      if (DestAppid != 0) hash ^= DestAppid.GetHashCode();
      if (MainCmdId != 0) hash ^= MainCmdId.GetHashCode();
      if (SubCmdId != 0) hash ^= SubCmdId.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (ClientIpV4 != 0) hash ^= ClientIpV4.GetHashCode();
      if (GateConnId != 0UL) hash ^= GateConnId.GetHashCode();
      if (UserId != 0UL) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DestApptype != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DestApptype);
      }
      if (DestAppid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(DestAppid);
      }
      if (MainCmdId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MainCmdId);
      }
      if (SubCmdId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(SubCmdId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Data);
      }
      if (ClientIpV4 != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ClientIpV4);
      }
      if (GateConnId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(GateConnId);
      }
      if (UserId != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DestApptype != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DestApptype);
      }
      if (DestAppid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(DestAppid);
      }
      if (MainCmdId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MainCmdId);
      }
      if (SubCmdId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(SubCmdId);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Data);
      }
      if (ClientIpV4 != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ClientIpV4);
      }
      if (GateConnId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(GateConnId);
      }
      if (UserId != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DestApptype != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DestApptype);
      }
      if (DestAppid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DestAppid);
      }
      if (MainCmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MainCmdId);
      }
      if (SubCmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SubCmdId);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (ClientIpV4 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ClientIpV4);
      }
      if (GateConnId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GateConnId);
      }
      if (UserId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransferDataReq other) {
      if (other == null) {
        return;
      }
      if (other.DestApptype != 0) {
        DestApptype = other.DestApptype;
      }
      if (other.DestAppid != 0) {
        DestAppid = other.DestAppid;
      }
      if (other.MainCmdId != 0) {
        MainCmdId = other.MainCmdId;
      }
      if (other.SubCmdId != 0) {
        SubCmdId = other.SubCmdId;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.ClientIpV4 != 0) {
        ClientIpV4 = other.ClientIpV4;
      }
      if (other.GateConnId != 0UL) {
        GateConnId = other.GateConnId;
      }
      if (other.UserId != 0UL) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DestApptype = input.ReadUInt32();
            break;
          }
          case 16: {
            DestAppid = input.ReadUInt32();
            break;
          }
          case 24: {
            MainCmdId = input.ReadUInt32();
            break;
          }
          case 32: {
            SubCmdId = input.ReadUInt32();
            break;
          }
          case 42: {
            Data = input.ReadBytes();
            break;
          }
          case 48: {
            ClientIpV4 = input.ReadUInt32();
            break;
          }
          case 56: {
            GateConnId = input.ReadUInt64();
            break;
          }
          case 64: {
            UserId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DestApptype = input.ReadUInt32();
            break;
          }
          case 16: {
            DestAppid = input.ReadUInt32();
            break;
          }
          case 24: {
            MainCmdId = input.ReadUInt32();
            break;
          }
          case 32: {
            SubCmdId = input.ReadUInt32();
            break;
          }
          case 42: {
            Data = input.ReadBytes();
            break;
          }
          case 48: {
            ClientIpV4 = input.ReadUInt32();
            break;
          }
          case 56: {
            GateConnId = input.ReadUInt64();
            break;
          }
          case 64: {
            UserId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///数据转发请求
  /// </summary>
  public sealed partial class TransferDataRsp : pb::IMessage<TransferDataRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransferDataRsp> _parser = new pb::MessageParser<TransferDataRsp>(() => new TransferDataRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransferDataRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataRsp(TransferDataRsp other) : this() {
      result_ = other.result_;
      reqId_ = other.reqId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransferDataRsp Clone() {
      return new TransferDataRsp(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "req_id" field.</summary>
    public const int ReqIdFieldNumber = 6;
    private uint reqId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ReqId {
      get { return reqId_; }
      set {
        reqId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransferDataRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransferDataRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (ReqId != other.ReqId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (ReqId != 0) hash ^= ReqId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (ReqId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ReqId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (ReqId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ReqId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      if (ReqId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ReqId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransferDataRsp other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.ReqId != 0) {
        ReqId = other.ReqId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 48: {
            ReqId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 48: {
            ReqId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///连接认证信息
  /// </summary>
  public sealed partial class AuthInfo : pb::IMessage<AuthInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthInfo> _parser = new pb::MessageParser<AuthInfo>(() => new AuthInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthInfo(AuthInfo other) : this() {
      userId_ = other.userId_;
      gateConnId_ = other.gateConnId_;
      result_ = other.result_;
      info_ = other.info_;
      opType_ = other.opType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthInfo Clone() {
      return new AuthInfo(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private ulong userId_;
    /// <summary>
    ///用户id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "gate_conn_id" field.</summary>
    public const int GateConnIdFieldNumber = 2;
    private ulong gateConnId_;
    /// <summary>
    ///gate连接id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong GateConnId {
      get { return gateConnId_; }
      set {
        gateConnId_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 3;
    private uint result_;
    /// <summary>
    ///结果 0成功
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 4;
    private string info_ = "";
    /// <summary>
    ///描述信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Info {
      get { return info_; }
      set {
        info_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "op_type" field.</summary>
    public const int OpTypeFieldNumber = 5;
    private global::Bs.Gateway.AuthInfo.Types.OpType opType_ = global::Bs.Gateway.AuthInfo.Types.OpType.Bind;
    /// <summary>
    ///操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Gateway.AuthInfo.Types.OpType OpType {
      get { return opType_; }
      set {
        opType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (GateConnId != other.GateConnId) return false;
      if (Result != other.Result) return false;
      if (Info != other.Info) return false;
      if (OpType != other.OpType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0UL) hash ^= UserId.GetHashCode();
      if (GateConnId != 0UL) hash ^= GateConnId.GetHashCode();
      if (Result != 0) hash ^= Result.GetHashCode();
      if (Info.Length != 0) hash ^= Info.GetHashCode();
      if (OpType != global::Bs.Gateway.AuthInfo.Types.OpType.Bind) hash ^= OpType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (GateConnId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(GateConnId);
      }
      if (Result != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Result);
      }
      if (Info.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Info);
      }
      if (OpType != global::Bs.Gateway.AuthInfo.Types.OpType.Bind) {
        output.WriteRawTag(40);
        output.WriteEnum((int) OpType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (GateConnId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(GateConnId);
      }
      if (Result != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Result);
      }
      if (Info.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Info);
      }
      if (OpType != global::Bs.Gateway.AuthInfo.Types.OpType.Bind) {
        output.WriteRawTag(40);
        output.WriteEnum((int) OpType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
      }
      if (GateConnId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GateConnId);
      }
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      if (Info.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Info);
      }
      if (OpType != global::Bs.Gateway.AuthInfo.Types.OpType.Bind) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OpType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthInfo other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0UL) {
        UserId = other.UserId;
      }
      if (other.GateConnId != 0UL) {
        GateConnId = other.GateConnId;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.Info.Length != 0) {
        Info = other.Info;
      }
      if (other.OpType != global::Bs.Gateway.AuthInfo.Types.OpType.Bind) {
        OpType = other.OpType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 16: {
            GateConnId = input.ReadUInt64();
            break;
          }
          case 24: {
            Result = input.ReadUInt32();
            break;
          }
          case 34: {
            Info = input.ReadString();
            break;
          }
          case 40: {
            OpType = (global::Bs.Gateway.AuthInfo.Types.OpType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 16: {
            GateConnId = input.ReadUInt64();
            break;
          }
          case 24: {
            Result = input.ReadUInt32();
            break;
          }
          case 34: {
            Info = input.ReadString();
            break;
          }
          case 40: {
            OpType = (global::Bs.Gateway.AuthInfo.Types.OpType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AuthInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum OpType {
        /// <summary>
        ///userId与connId绑定
        /// </summary>
        [pbr::OriginalName("Bind")] Bind = 0,
        /// <summary>
        ///断开当前connId连接
        /// </summary>
        [pbr::OriginalName("Disconnect")] Disconnect = 1,
      }

    }
    #endregion

  }

  /// <summary>
  ///握手请求
  /// </summary>
  public sealed partial class HelloReq : pb::IMessage<HelloReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HelloReq> _parser = new pb::MessageParser<HelloReq>(() => new HelloReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HelloReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloReq(HelloReq other) : this() {
      adId_ = other.adId_;
      others_ = other.others_;
      builderNo_ = other.builderNo_;
      gameKind_ = other.gameKind_;
      clientVersion_ = other.clientVersion_;
      clientType_ = other.clientType_;
      publicKey_ = other.publicKey_;
      encryptKey_ = other.encryptKey_;
      guid_ = other.guid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloReq Clone() {
      return new HelloReq(this);
    }

    /// <summary>Field number for the "ad_id" field.</summary>
    public const int AdIdFieldNumber = 2;
    private uint adId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AdId {
      get { return adId_; }
      set {
        adId_ = value;
      }
    }

    /// <summary>Field number for the "others" field.</summary>
    public const int OthersFieldNumber = 3;
    private string others_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Others {
      get { return others_; }
      set {
        others_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "builder_no" field.</summary>
    public const int BuilderNoFieldNumber = 4;
    private uint builderNo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BuilderNo {
      get { return builderNo_; }
      set {
        builderNo_ = value;
      }
    }

    /// <summary>Field number for the "game_kind" field.</summary>
    public const int GameKindFieldNumber = 5;
    private uint gameKind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GameKind {
      get { return gameKind_; }
      set {
        gameKind_ = value;
      }
    }

    /// <summary>Field number for the "client_version" field.</summary>
    public const int ClientVersionFieldNumber = 6;
    private string clientVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientVersion {
      get { return clientVersion_; }
      set {
        clientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_type" field.</summary>
    public const int ClientTypeFieldNumber = 7;
    private uint clientType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ClientType {
      get { return clientType_; }
      set {
        clientType_ = value;
      }
    }

    /// <summary>Field number for the "public_key" field.</summary>
    public const int PublicKeyFieldNumber = 8;
    private string publicKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublicKey {
      get { return publicKey_; }
      set {
        publicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encrypt_key" field.</summary>
    public const int EncryptKeyFieldNumber = 9;
    private string encryptKey_ = "";
    /// <summary>
    ///加密key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EncryptKey {
      get { return encryptKey_; }
      set {
        encryptKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 10;
    private string guid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Guid {
      get { return guid_; }
      set {
        guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HelloReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HelloReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AdId != other.AdId) return false;
      if (Others != other.Others) return false;
      if (BuilderNo != other.BuilderNo) return false;
      if (GameKind != other.GameKind) return false;
      if (ClientVersion != other.ClientVersion) return false;
      if (ClientType != other.ClientType) return false;
      if (PublicKey != other.PublicKey) return false;
      if (EncryptKey != other.EncryptKey) return false;
      if (Guid != other.Guid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AdId != 0) hash ^= AdId.GetHashCode();
      if (Others.Length != 0) hash ^= Others.GetHashCode();
      if (BuilderNo != 0) hash ^= BuilderNo.GetHashCode();
      if (GameKind != 0) hash ^= GameKind.GetHashCode();
      if (ClientVersion.Length != 0) hash ^= ClientVersion.GetHashCode();
      if (ClientType != 0) hash ^= ClientType.GetHashCode();
      if (PublicKey.Length != 0) hash ^= PublicKey.GetHashCode();
      if (EncryptKey.Length != 0) hash ^= EncryptKey.GetHashCode();
      if (Guid.Length != 0) hash ^= Guid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AdId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AdId);
      }
      if (Others.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Others);
      }
      if (BuilderNo != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BuilderNo);
      }
      if (GameKind != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(GameKind);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ClientVersion);
      }
      if (ClientType != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(ClientType);
      }
      if (PublicKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(PublicKey);
      }
      if (EncryptKey.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(EncryptKey);
      }
      if (Guid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Guid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AdId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AdId);
      }
      if (Others.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Others);
      }
      if (BuilderNo != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BuilderNo);
      }
      if (GameKind != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(GameKind);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ClientVersion);
      }
      if (ClientType != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(ClientType);
      }
      if (PublicKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(PublicKey);
      }
      if (EncryptKey.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(EncryptKey);
      }
      if (Guid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Guid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AdId);
      }
      if (Others.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Others);
      }
      if (BuilderNo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BuilderNo);
      }
      if (GameKind != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameKind);
      }
      if (ClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientVersion);
      }
      if (ClientType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ClientType);
      }
      if (PublicKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicKey);
      }
      if (EncryptKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptKey);
      }
      if (Guid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HelloReq other) {
      if (other == null) {
        return;
      }
      if (other.AdId != 0) {
        AdId = other.AdId;
      }
      if (other.Others.Length != 0) {
        Others = other.Others;
      }
      if (other.BuilderNo != 0) {
        BuilderNo = other.BuilderNo;
      }
      if (other.GameKind != 0) {
        GameKind = other.GameKind;
      }
      if (other.ClientVersion.Length != 0) {
        ClientVersion = other.ClientVersion;
      }
      if (other.ClientType != 0) {
        ClientType = other.ClientType;
      }
      if (other.PublicKey.Length != 0) {
        PublicKey = other.PublicKey;
      }
      if (other.EncryptKey.Length != 0) {
        EncryptKey = other.EncryptKey;
      }
      if (other.Guid.Length != 0) {
        Guid = other.Guid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            AdId = input.ReadUInt32();
            break;
          }
          case 26: {
            Others = input.ReadString();
            break;
          }
          case 32: {
            BuilderNo = input.ReadUInt32();
            break;
          }
          case 40: {
            GameKind = input.ReadUInt32();
            break;
          }
          case 50: {
            ClientVersion = input.ReadString();
            break;
          }
          case 56: {
            ClientType = input.ReadUInt32();
            break;
          }
          case 66: {
            PublicKey = input.ReadString();
            break;
          }
          case 74: {
            EncryptKey = input.ReadString();
            break;
          }
          case 82: {
            Guid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            AdId = input.ReadUInt32();
            break;
          }
          case 26: {
            Others = input.ReadString();
            break;
          }
          case 32: {
            BuilderNo = input.ReadUInt32();
            break;
          }
          case 40: {
            GameKind = input.ReadUInt32();
            break;
          }
          case 50: {
            ClientVersion = input.ReadString();
            break;
          }
          case 56: {
            ClientType = input.ReadUInt32();
            break;
          }
          case 66: {
            PublicKey = input.ReadString();
            break;
          }
          case 74: {
            EncryptKey = input.ReadString();
            break;
          }
          case 82: {
            Guid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///握手回复
  /// </summary>
  public sealed partial class HelloRsp : pb::IMessage<HelloRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HelloRsp> _parser = new pb::MessageParser<HelloRsp>(() => new HelloRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HelloRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Gateway.GatewayReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloRsp(HelloRsp other) : this() {
      rspFlag_ = other.rspFlag_;
      gateAddress_ = other.gateAddress_.Clone();
      loginToken_ = other.loginToken_;
      publicKey_ = other.publicKey_;
      encryptKey_ = other.encryptKey_;
      versionResult_ = other.versionResult_;
      downUrl_ = other.downUrl_;
      guid_ = other.guid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HelloRsp Clone() {
      return new HelloRsp(this);
    }

    /// <summary>Field number for the "rsp_flag" field.</summary>
    public const int RspFlagFieldNumber = 1;
    private uint rspFlag_;
    /// <summary>
    ///通知的消息内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RspFlag {
      get { return rspFlag_; }
      set {
        rspFlag_ = value;
      }
    }

    /// <summary>Field number for the "gate_address" field.</summary>
    public const int GateAddressFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_gateAddress_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> gateAddress_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///当前最新的gate地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> GateAddress {
      get { return gateAddress_; }
    }

    /// <summary>Field number for the "login_token" field.</summary>
    public const int LoginTokenFieldNumber = 4;
    private uint loginToken_;
    /// <summary>
    ///登录令牌
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LoginToken {
      get { return loginToken_; }
      set {
        loginToken_ = value;
      }
    }

    /// <summary>Field number for the "public_key" field.</summary>
    public const int PublicKeyFieldNumber = 8;
    private string publicKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PublicKey {
      get { return publicKey_; }
      set {
        publicKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encrypt_key" field.</summary>
    public const int EncryptKeyFieldNumber = 3;
    private string encryptKey_ = "";
    /// <summary>
    ///加密key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EncryptKey {
      get { return encryptKey_; }
      set {
        encryptKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version_result" field.</summary>
    public const int VersionResultFieldNumber = 5;
    private uint versionResult_;
    /// <summary>
    ///
    ///=0 表示是最新版本
    ///=1 表示有新版本,但当前版本还可以用
    ///=2 表示老版本必须更新了,当前连接会被断开的
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint VersionResult {
      get { return versionResult_; }
      set {
        versionResult_ = value;
      }
    }

    /// <summary>Field number for the "down_url" field.</summary>
    public const int DownUrlFieldNumber = 6;
    private string downUrl_ = "";
    /// <summary>
    ///
    ///如果有新的版本,下载地址(一般用于手机)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DownUrl {
      get { return downUrl_; }
      set {
        downUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 7;
    private string guid_ = "";
    /// <summary>
    ///如果Req的guid为空，则这里为其创建一个guid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Guid {
      get { return guid_; }
      set {
        guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HelloRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HelloRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RspFlag != other.RspFlag) return false;
      if(!gateAddress_.Equals(other.gateAddress_)) return false;
      if (LoginToken != other.LoginToken) return false;
      if (PublicKey != other.PublicKey) return false;
      if (EncryptKey != other.EncryptKey) return false;
      if (VersionResult != other.VersionResult) return false;
      if (DownUrl != other.DownUrl) return false;
      if (Guid != other.Guid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RspFlag != 0) hash ^= RspFlag.GetHashCode();
      hash ^= gateAddress_.GetHashCode();
      if (LoginToken != 0) hash ^= LoginToken.GetHashCode();
      if (PublicKey.Length != 0) hash ^= PublicKey.GetHashCode();
      if (EncryptKey.Length != 0) hash ^= EncryptKey.GetHashCode();
      if (VersionResult != 0) hash ^= VersionResult.GetHashCode();
      if (DownUrl.Length != 0) hash ^= DownUrl.GetHashCode();
      if (Guid.Length != 0) hash ^= Guid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RspFlag != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RspFlag);
      }
      gateAddress_.WriteTo(output, _repeated_gateAddress_codec);
      if (EncryptKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EncryptKey);
      }
      if (LoginToken != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LoginToken);
      }
      if (VersionResult != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(VersionResult);
      }
      if (DownUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DownUrl);
      }
      if (Guid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Guid);
      }
      if (PublicKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(PublicKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RspFlag != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RspFlag);
      }
      gateAddress_.WriteTo(ref output, _repeated_gateAddress_codec);
      if (EncryptKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EncryptKey);
      }
      if (LoginToken != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LoginToken);
      }
      if (VersionResult != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(VersionResult);
      }
      if (DownUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DownUrl);
      }
      if (Guid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Guid);
      }
      if (PublicKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(PublicKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RspFlag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RspFlag);
      }
      size += gateAddress_.CalculateSize(_repeated_gateAddress_codec);
      if (LoginToken != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LoginToken);
      }
      if (PublicKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PublicKey);
      }
      if (EncryptKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptKey);
      }
      if (VersionResult != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VersionResult);
      }
      if (DownUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DownUrl);
      }
      if (Guid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HelloRsp other) {
      if (other == null) {
        return;
      }
      if (other.RspFlag != 0) {
        RspFlag = other.RspFlag;
      }
      gateAddress_.Add(other.gateAddress_);
      if (other.LoginToken != 0) {
        LoginToken = other.LoginToken;
      }
      if (other.PublicKey.Length != 0) {
        PublicKey = other.PublicKey;
      }
      if (other.EncryptKey.Length != 0) {
        EncryptKey = other.EncryptKey;
      }
      if (other.VersionResult != 0) {
        VersionResult = other.VersionResult;
      }
      if (other.DownUrl.Length != 0) {
        DownUrl = other.DownUrl;
      }
      if (other.Guid.Length != 0) {
        Guid = other.Guid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RspFlag = input.ReadUInt32();
            break;
          }
          case 18: {
            gateAddress_.AddEntriesFrom(input, _repeated_gateAddress_codec);
            break;
          }
          case 26: {
            EncryptKey = input.ReadString();
            break;
          }
          case 32: {
            LoginToken = input.ReadUInt32();
            break;
          }
          case 40: {
            VersionResult = input.ReadUInt32();
            break;
          }
          case 50: {
            DownUrl = input.ReadString();
            break;
          }
          case 58: {
            Guid = input.ReadString();
            break;
          }
          case 66: {
            PublicKey = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RspFlag = input.ReadUInt32();
            break;
          }
          case 18: {
            gateAddress_.AddEntriesFrom(ref input, _repeated_gateAddress_codec);
            break;
          }
          case 26: {
            EncryptKey = input.ReadString();
            break;
          }
          case 32: {
            LoginToken = input.ReadUInt32();
            break;
          }
          case 40: {
            VersionResult = input.ReadUInt32();
            break;
          }
          case 50: {
            DownUrl = input.ReadString();
            break;
          }
          case 58: {
            Guid = input.ReadString();
            break;
          }
          case 66: {
            PublicKey = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the HelloRsp message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RspFlag {
        /// <summary>
        ///未知
        /// </summary>
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        /// <summary>
        ///加密信息   encrypt_key 这是存在的
        /// </summary>
        [pbr::OriginalName("EncryptInfo")] EncryptInfo = 1,
        /// <summary>
        ///建议去新的gate，这时gate_address 必须有内容
        /// </summary>
        [pbr::OriginalName("AdviceNewGate")] AdviceNewGate = 2,
        /// <summary>
        ///登录令牌
        /// </summary>
        [pbr::OriginalName("LoginToken")] LoginToken = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
