//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: list.proto
// Note: requires additional types generated from: types.proto
namespace bs.list
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomRegisterReq")]
  public partial class RoomRegisterReq : global::ProtoBuf.IExtensible
  {
    public RoomRegisterReq() {}
    
    private bs.types.RoomInfo _info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bs.types.RoomInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomRegisterRsp")]
  public partial class RoomRegisterRsp : global::ProtoBuf.IExtensible
  {
    public RoomRegisterRsp() {}
    
    private bs.types.ErrorInfo _err_info = null;
    [global::ProtoBuf.ProtoMember(99, IsRequired = false, Name=@"err_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bs.types.ErrorInfo err_info
    {
      get { return _err_info; }
      set { _err_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomListReq")]
  public partial class RoomListReq : global::ProtoBuf.IExtensible
  {
    public RoomListReq() {}
    
    private uint _list_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"list_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint list_id
    {
      get { return _list_id; }
      set { _list_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomListRsp")]
  public partial class RoomListRsp : global::ProtoBuf.IExtensible
  {
    public RoomListRsp() {}
    
    private readonly global::System.Collections.Generic.List<bs.types.RoomInfo> _rooms = new global::System.Collections.Generic.List<bs.types.RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bs.types.RoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMDList")]
    public enum CMDList
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDRoomRegisterReq", Value=1)]
      IDRoomRegisterReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDRoomRegisterRsp", Value=2)]
      IDRoomRegisterRsp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDRoomListReq", Value=3)]
      IDRoomListReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDRoomListRsp", Value=4)]
      IDRoomListRsp = 4
    }
  
}