// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bs.Lobby {

  /// <summary>Holder for reflection information generated from lobby.proto</summary>
  public static partial class LobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for lobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtsb2JieS5wcm90bxIIYnMubG9iYnkaC3R5cGVzLnByb3RvIqQCCghMb2dp",
            "blJlcRIRCglnYW1lX2tpbmQYASABKA0SMAoKbG9naW5fdHlwZRgCIAEoDjIc",
            "LmJzLmxvYmJ5LkxvZ2luUmVxLkxvZ2luVHlwZRIPCgdhY2NvdW50GAMgASgJ",
            "EhAKCHBhc3N3b3JkGAQgASgJEg8KB3ZlcnNpb24YBSABKAkSCgoCSVAYBiAB",
            "KAkSFgoOc3lzdGVtX3ZlcnNpb24YByABKAkSEgoKY2hhbm5lbF9pZBgIIAEo",
            "DRIPCgdzaXRlX2lkGAkgASgNEhEKCWRldmljZV9pZBgKIAEoCRIRCgl1c2Vy",
            "X3R5cGUYCyABKAUiMAoJTG9naW5UeXBlEgsKB0FjY291bnQQABIJCgVUb2tl",
            "bhABEgsKB1VuaW9uSWQQAiKiAwoITG9naW5Sc3ASKQoGcmVzdWx0GAEgASgO",
            "MhkuYnMubG9iYnkuTG9naW5Sc3AuUmVzdWx0EikKCWJhc2VfaW5mbxgCIAEo",
            "CzIWLmJzLnR5cGVzLkJhc2VVc2VySW5mbxIlCghlcnJfaW5mbxhjIAEoCzIT",
            "LmJzLnR5cGVzLkVycm9ySW5mbyKYAgoGUmVzdWx0EgsKB1NVQ0NFU1MQABIM",
            "CghOT1RFWElTVBABEgoKBkZST1pFThACEgsKB0ZBTFNFUFcQAxIMCghORVRF",
            "UlJPUhAEEg0KCUFQUElTQlVTWRAFEg8KC0dVRVNURk9SQklEEAYSEAoMQ09O",
            "TkVDVEVSUk9SEAcSDgoKVkVSU0lPTk9MRBAIEg8KC05PTU9SRUdVRVNUEAkS",
            "DgoKRlJFUVVFTlRMWRAKEg4KCkFQUElOSVRJTkcQCxIQCgtTRVJWRVJFUlJP",
            "UhD/ARILCgZVTktPV04Q6AcSEQoMVE9LRU5fRkFJTEVEEOkHEhIKDVRPS0VO",
            "X0VYUElSRUQQ6gcSEwoOVE9LRU5fTk9UTUFUQ0gQ6wciMAoJTG9nb3V0UmVx",
            "Eg8KB3VzZXJfaWQYASACKAQSEgoKR2F0ZUNvbm5JZBgCIAEoBCKSAQoJTG9n",
            "b3V0UnNwEjAKBnJlYXNvbhgBIAEoDjIgLmJzLmxvYmJ5LkxvZ291dFJzcC5M",
            "b2dvdXRSZWFzb24SJQoIZXJyX2luZm8YYyABKAsyEy5icy50eXBlcy5FcnJv",
            "ckluZm8iLAoMTG9nb3V0UmVhc29uEgoKBk5vcm1hbBAAEhAKDEFub3RoZXJM",
            "b2dpbhABIg0KC0xvZ2ljUmVnUmVxIjQKC0xvZ2ljUmVnUnNwEiUKCGVycl9p",
            "bmZvGGMgASgLMhMuYnMudHlwZXMuRXJyb3JJbmZvIsEBCg9Vc2VyT25saW5l",
            "U3RhdGUSKQoJdXNlcl9pbmZvGAEgASgLMhYuYnMudHlwZXMuQmFzZVVzZXJJ",
            "bmZvEjoKDG9ubGluZV9zdGF0ZRgCIAEoDjIkLmJzLmxvYmJ5LlVzZXJPbmxp",
            "bmVTdGF0ZS5PbmxpbmVTdGF0IkcKCk9ubGluZVN0YXQSCgoGT25saW5lEAES",
            "EQoNRGlzY29ubmVjdGlvbhACEg0KCVJlY29ubmVjdBADEgsKB09mZmxpbmUQ",
            "BCqDAQoIQ01ETG9iYnkSDgoKSURMb2dpblJlcRABEg4KCklETG9naW5Sc3AQ",
            "AhIPCgtJRExvZ291dFJlcRADEg8KC0lETG9nb3V0UnNwEAQSEQoNSURMb2dp",
            "Y1JlZ1JlcRAFEhEKDUlETG9naWNSZWdSc3AQBhIPCgtJRFVzZXJTdGF0ZRAH",
            "QghaBi9sb2JieQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bs.Types.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bs.Lobby.CMDLobby), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LoginReq), global::Bs.Lobby.LoginReq.Parser, new[]{ "GameKind", "LoginType", "Account", "Password", "Version", "IP", "SystemVersion", "ChannelId", "SiteId", "DeviceId", "UserType" }, null, new[]{ typeof(global::Bs.Lobby.LoginReq.Types.LoginType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LoginRsp), global::Bs.Lobby.LoginRsp.Parser, new[]{ "Result", "BaseInfo", "ErrInfo" }, null, new[]{ typeof(global::Bs.Lobby.LoginRsp.Types.Result) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LogoutReq), global::Bs.Lobby.LogoutReq.Parser, new[]{ "UserId", "GateConnId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LogoutRsp), global::Bs.Lobby.LogoutRsp.Parser, new[]{ "Reason", "ErrInfo" }, null, new[]{ typeof(global::Bs.Lobby.LogoutRsp.Types.LogoutReason) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LogicRegReq), global::Bs.Lobby.LogicRegReq.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.LogicRegRsp), global::Bs.Lobby.LogicRegRsp.Parser, new[]{ "ErrInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bs.Lobby.UserOnlineState), global::Bs.Lobby.UserOnlineState.Parser, new[]{ "UserInfo", "OnlineState" }, null, new[]{ typeof(global::Bs.Lobby.UserOnlineState.Types.OnlineStat) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CMDLobby {
    /// <summary>
    ///登录请求
    /// </summary>
    [pbr::OriginalName("IDLoginReq")] IdloginReq = 1,
    /// <summary>
    ///登录回复
    /// </summary>
    [pbr::OriginalName("IDLoginRsp")] IdloginRsp = 2,
    /// <summary>
    ///注销登录
    /// </summary>
    [pbr::OriginalName("IDLogoutReq")] IdlogoutReq = 3,
    /// <summary>
    ///注销登录
    /// </summary>
    [pbr::OriginalName("IDLogoutRsp")] IdlogoutRsp = 4,
    /// <summary>
    ///逻辑注册
    /// </summary>
    [pbr::OriginalName("IDLogicRegReq")] IdlogicRegReq = 5,
    /// <summary>
    ///逻辑注册
    /// </summary>
    [pbr::OriginalName("IDLogicRegRsp")] IdlogicRegRsp = 6,
    /// <summary>
    ///用户状态
    /// </summary>
    [pbr::OriginalName("IDUserState")] IduserState = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  ///登录请求
  /// </summary>
  public sealed partial class LoginReq : pb::IMessage<LoginReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq(LoginReq other) : this() {
      _hasBits0 = other._hasBits0;
      gameKind_ = other.gameKind_;
      loginType_ = other.loginType_;
      account_ = other.account_;
      password_ = other.password_;
      version_ = other.version_;
      iP_ = other.iP_;
      systemVersion_ = other.systemVersion_;
      channelId_ = other.channelId_;
      siteId_ = other.siteId_;
      deviceId_ = other.deviceId_;
      userType_ = other.userType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq Clone() {
      return new LoginReq(this);
    }

    /// <summary>Field number for the "game_kind" field.</summary>
    public const int GameKindFieldNumber = 1;
    private readonly static uint GameKindDefaultValue = 0;

    private uint gameKind_;
    /// <summary>
    ///游戏种类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GameKind {
      get { if ((_hasBits0 & 1) != 0) { return gameKind_; } else { return GameKindDefaultValue; } }
      set {
        _hasBits0 |= 1;
        gameKind_ = value;
      }
    }
    /// <summary>Gets whether the "game_kind" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGameKind {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "game_kind" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGameKind() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "login_type" field.</summary>
    public const int LoginTypeFieldNumber = 2;
    private readonly static global::Bs.Lobby.LoginReq.Types.LoginType LoginTypeDefaultValue = global::Bs.Lobby.LoginReq.Types.LoginType.Account;

    private global::Bs.Lobby.LoginReq.Types.LoginType loginType_;
    /// <summary>
    ///登录类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Lobby.LoginReq.Types.LoginType LoginType {
      get { if ((_hasBits0 & 2) != 0) { return loginType_; } else { return LoginTypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        loginType_ = value;
      }
    }
    /// <summary>Gets whether the "login_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLoginType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "login_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLoginType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 3;
    private readonly static string AccountDefaultValue = "";

    private string account_;
    /// <summary>
    ///用户账号(根据 LoginAction填不通内容)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Account {
      get { return account_ ?? AccountDefaultValue; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "account" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccount {
      get { return account_ != null; }
    }
    /// <summary>Clears the value of the "account" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccount() {
      account_ = null;
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 4;
    private readonly static string PasswordDefaultValue = "";

    private string password_;
    /// <summary>
    ///用户密码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_ ?? PasswordDefaultValue; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "password" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPassword {
      get { return password_ != null; }
    }
    /// <summary>Clears the value of the "password" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPassword() {
      password_ = null;
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 5;
    private readonly static string VersionDefaultValue = "";

    private string version_;
    /// <summary>
    ///客户端版本号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_ ?? VersionDefaultValue; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "version" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVersion {
      get { return version_ != null; }
    }
    /// <summary>Clears the value of the "version" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVersion() {
      version_ = null;
    }

    /// <summary>Field number for the "IP" field.</summary>
    public const int IPFieldNumber = 6;
    private readonly static string IPDefaultValue = "";

    private string iP_;
    /// <summary>
    ///客户端IP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IP {
      get { return iP_ ?? IPDefaultValue; }
      set {
        iP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "IP" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIP {
      get { return iP_ != null; }
    }
    /// <summary>Clears the value of the "IP" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIP() {
      iP_ = null;
    }

    /// <summary>Field number for the "system_version" field.</summary>
    public const int SystemVersionFieldNumber = 7;
    private readonly static string SystemVersionDefaultValue = "";

    private string systemVersion_;
    /// <summary>
    ///操作系统版本号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SystemVersion {
      get { return systemVersion_ ?? SystemVersionDefaultValue; }
      set {
        systemVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "system_version" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSystemVersion {
      get { return systemVersion_ != null; }
    }
    /// <summary>Clears the value of the "system_version" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSystemVersion() {
      systemVersion_ = null;
    }

    /// <summary>Field number for the "channel_id" field.</summary>
    public const int ChannelIdFieldNumber = 8;
    private readonly static uint ChannelIdDefaultValue = 0;

    private uint channelId_;
    /// <summary>
    ///主渠道id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChannelId {
      get { if ((_hasBits0 & 4) != 0) { return channelId_; } else { return ChannelIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        channelId_ = value;
      }
    }
    /// <summary>Gets whether the "channel_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasChannelId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "channel_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearChannelId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "site_id" field.</summary>
    public const int SiteIdFieldNumber = 9;
    private readonly static uint SiteIdDefaultValue = 0;

    private uint siteId_;
    /// <summary>
    ///子渠道id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SiteId {
      get { if ((_hasBits0 & 8) != 0) { return siteId_; } else { return SiteIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        siteId_ = value;
      }
    }
    /// <summary>Gets whether the "site_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSiteId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "site_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSiteId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "device_id" field.</summary>
    public const int DeviceIdFieldNumber = 10;
    private readonly static string DeviceIdDefaultValue = "";

    private string deviceId_;
    /// <summary>
    ///设备唯一码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_ ?? DeviceIdDefaultValue; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "device_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeviceId {
      get { return deviceId_ != null; }
    }
    /// <summary>Clears the value of the "device_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeviceId() {
      deviceId_ = null;
    }

    /// <summary>Field number for the "user_type" field.</summary>
    public const int UserTypeFieldNumber = 11;
    private readonly static int UserTypeDefaultValue = 0;

    private int userType_;
    /// <summary>
    ///用户类型(客户端禁止使用)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserType {
      get { if ((_hasBits0 & 16) != 0) { return userType_; } else { return UserTypeDefaultValue; } }
      set {
        _hasBits0 |= 16;
        userType_ = value;
      }
    }
    /// <summary>Gets whether the "user_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUserType {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "user_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUserType() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameKind != other.GameKind) return false;
      if (LoginType != other.LoginType) return false;
      if (Account != other.Account) return false;
      if (Password != other.Password) return false;
      if (Version != other.Version) return false;
      if (IP != other.IP) return false;
      if (SystemVersion != other.SystemVersion) return false;
      if (ChannelId != other.ChannelId) return false;
      if (SiteId != other.SiteId) return false;
      if (DeviceId != other.DeviceId) return false;
      if (UserType != other.UserType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasGameKind) hash ^= GameKind.GetHashCode();
      if (HasLoginType) hash ^= LoginType.GetHashCode();
      if (HasAccount) hash ^= Account.GetHashCode();
      if (HasPassword) hash ^= Password.GetHashCode();
      if (HasVersion) hash ^= Version.GetHashCode();
      if (HasIP) hash ^= IP.GetHashCode();
      if (HasSystemVersion) hash ^= SystemVersion.GetHashCode();
      if (HasChannelId) hash ^= ChannelId.GetHashCode();
      if (HasSiteId) hash ^= SiteId.GetHashCode();
      if (HasDeviceId) hash ^= DeviceId.GetHashCode();
      if (HasUserType) hash ^= UserType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasGameKind) {
        output.WriteRawTag(8);
        output.WriteUInt32(GameKind);
      }
      if (HasLoginType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) LoginType);
      }
      if (HasAccount) {
        output.WriteRawTag(26);
        output.WriteString(Account);
      }
      if (HasPassword) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (HasVersion) {
        output.WriteRawTag(42);
        output.WriteString(Version);
      }
      if (HasIP) {
        output.WriteRawTag(50);
        output.WriteString(IP);
      }
      if (HasSystemVersion) {
        output.WriteRawTag(58);
        output.WriteString(SystemVersion);
      }
      if (HasChannelId) {
        output.WriteRawTag(64);
        output.WriteUInt32(ChannelId);
      }
      if (HasSiteId) {
        output.WriteRawTag(72);
        output.WriteUInt32(SiteId);
      }
      if (HasDeviceId) {
        output.WriteRawTag(82);
        output.WriteString(DeviceId);
      }
      if (HasUserType) {
        output.WriteRawTag(88);
        output.WriteInt32(UserType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasGameKind) {
        output.WriteRawTag(8);
        output.WriteUInt32(GameKind);
      }
      if (HasLoginType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) LoginType);
      }
      if (HasAccount) {
        output.WriteRawTag(26);
        output.WriteString(Account);
      }
      if (HasPassword) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (HasVersion) {
        output.WriteRawTag(42);
        output.WriteString(Version);
      }
      if (HasIP) {
        output.WriteRawTag(50);
        output.WriteString(IP);
      }
      if (HasSystemVersion) {
        output.WriteRawTag(58);
        output.WriteString(SystemVersion);
      }
      if (HasChannelId) {
        output.WriteRawTag(64);
        output.WriteUInt32(ChannelId);
      }
      if (HasSiteId) {
        output.WriteRawTag(72);
        output.WriteUInt32(SiteId);
      }
      if (HasDeviceId) {
        output.WriteRawTag(82);
        output.WriteString(DeviceId);
      }
      if (HasUserType) {
        output.WriteRawTag(88);
        output.WriteInt32(UserType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasGameKind) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameKind);
      }
      if (HasLoginType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LoginType);
      }
      if (HasAccount) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (HasPassword) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (HasVersion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (HasIP) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IP);
      }
      if (HasSystemVersion) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SystemVersion);
      }
      if (HasChannelId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChannelId);
      }
      if (HasSiteId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SiteId);
      }
      if (HasDeviceId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (HasUserType) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginReq other) {
      if (other == null) {
        return;
      }
      if (other.HasGameKind) {
        GameKind = other.GameKind;
      }
      if (other.HasLoginType) {
        LoginType = other.LoginType;
      }
      if (other.HasAccount) {
        Account = other.Account;
      }
      if (other.HasPassword) {
        Password = other.Password;
      }
      if (other.HasVersion) {
        Version = other.Version;
      }
      if (other.HasIP) {
        IP = other.IP;
      }
      if (other.HasSystemVersion) {
        SystemVersion = other.SystemVersion;
      }
      if (other.HasChannelId) {
        ChannelId = other.ChannelId;
      }
      if (other.HasSiteId) {
        SiteId = other.SiteId;
      }
      if (other.HasDeviceId) {
        DeviceId = other.DeviceId;
      }
      if (other.HasUserType) {
        UserType = other.UserType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameKind = input.ReadUInt32();
            break;
          }
          case 16: {
            LoginType = (global::Bs.Lobby.LoginReq.Types.LoginType) input.ReadEnum();
            break;
          }
          case 26: {
            Account = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
          case 42: {
            Version = input.ReadString();
            break;
          }
          case 50: {
            IP = input.ReadString();
            break;
          }
          case 58: {
            SystemVersion = input.ReadString();
            break;
          }
          case 64: {
            ChannelId = input.ReadUInt32();
            break;
          }
          case 72: {
            SiteId = input.ReadUInt32();
            break;
          }
          case 82: {
            DeviceId = input.ReadString();
            break;
          }
          case 88: {
            UserType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameKind = input.ReadUInt32();
            break;
          }
          case 16: {
            LoginType = (global::Bs.Lobby.LoginReq.Types.LoginType) input.ReadEnum();
            break;
          }
          case 26: {
            Account = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
          case 42: {
            Version = input.ReadString();
            break;
          }
          case 50: {
            IP = input.ReadString();
            break;
          }
          case 58: {
            SystemVersion = input.ReadString();
            break;
          }
          case 64: {
            ChannelId = input.ReadUInt32();
            break;
          }
          case 72: {
            SiteId = input.ReadUInt32();
            break;
          }
          case 82: {
            DeviceId = input.ReadString();
            break;
          }
          case 88: {
            UserType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LoginReq message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LoginType {
        /// <summary>
        ///账号
        /// </summary>
        [pbr::OriginalName("Account")] Account = 0,
        /// <summary>
        /// </summary>
        [pbr::OriginalName("Token")] Token = 1,
        /// <summary>
        ///唯一标识(游客登录等)
        /// </summary>
        [pbr::OriginalName("UnionId")] UnionId = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// 登录回复
  /// </summary>
  public sealed partial class LoginRsp : pb::IMessage<LoginRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginRsp> _parser = new pb::MessageParser<LoginRsp>(() => new LoginRsp());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRsp(LoginRsp other) : this() {
      _hasBits0 = other._hasBits0;
      result_ = other.result_;
      baseInfo_ = other.baseInfo_ != null ? other.baseInfo_.Clone() : null;
      errInfo_ = other.errInfo_ != null ? other.errInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRsp Clone() {
      return new LoginRsp(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private readonly static global::Bs.Lobby.LoginRsp.Types.Result ResultDefaultValue = global::Bs.Lobby.LoginRsp.Types.Result.Success;

    private global::Bs.Lobby.LoginRsp.Types.Result result_;
    /// <summary>
    ///登录结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Lobby.LoginRsp.Types.Result Result {
      get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
      set {
        _hasBits0 |= 1;
        result_ = value;
      }
    }
    /// <summary>Gets whether the "result" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResult {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "result" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResult() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "base_info" field.</summary>
    public const int BaseInfoFieldNumber = 2;
    private global::Bs.Types.BaseUserInfo baseInfo_;
    /// <summary>
    ///基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Types.BaseUserInfo BaseInfo {
      get { return baseInfo_; }
      set {
        baseInfo_ = value;
      }
    }

    /// <summary>Field number for the "err_info" field.</summary>
    public const int ErrInfoFieldNumber = 99;
    private global::Bs.Types.ErrorInfo errInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Types.ErrorInfo ErrInfo {
      get { return errInfo_; }
      set {
        errInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(BaseInfo, other.BaseInfo)) return false;
      if (!object.Equals(ErrInfo, other.ErrInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasResult) hash ^= Result.GetHashCode();
      if (baseInfo_ != null) hash ^= BaseInfo.GetHashCode();
      if (errInfo_ != null) hash ^= ErrInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasResult) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (baseInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BaseInfo);
      }
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasResult) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (baseInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BaseInfo);
      }
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasResult) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (baseInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseInfo);
      }
      if (errInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ErrInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginRsp other) {
      if (other == null) {
        return;
      }
      if (other.HasResult) {
        Result = other.Result;
      }
      if (other.baseInfo_ != null) {
        if (baseInfo_ == null) {
          BaseInfo = new global::Bs.Types.BaseUserInfo();
        }
        BaseInfo.MergeFrom(other.BaseInfo);
      }
      if (other.errInfo_ != null) {
        if (errInfo_ == null) {
          ErrInfo = new global::Bs.Types.ErrorInfo();
        }
        ErrInfo.MergeFrom(other.ErrInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Bs.Lobby.LoginRsp.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Bs.Types.BaseUserInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Bs.Lobby.LoginRsp.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Bs.Types.BaseUserInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LoginRsp message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Result {
        /// <summary>
        ///成功
        /// </summary>
        [pbr::OriginalName("SUCCESS")] Success = 0,
        /// <summary>
        ///账号不存在
        /// </summary>
        [pbr::OriginalName("NOTEXIST")] Notexist = 1,
        /// <summary>
        ///账号被冻结
        /// </summary>
        [pbr::OriginalName("FROZEN")] Frozen = 2,
        /// <summary>
        ///密码错误	
        /// </summary>
        [pbr::OriginalName("FALSEPW")] Falsepw = 3,
        /// <summary>
        ///网络异常	
        /// </summary>
        [pbr::OriginalName("NETERROR")] Neterror = 4,
        /// <summary>
        ///服务器忙，人数爆满
        /// </summary>
        [pbr::OriginalName("APPISBUSY")] Appisbusy = 5,
        /// <summary>
        ///禁止游客登录
        /// </summary>
        [pbr::OriginalName("GUESTFORBID")] Guestforbid = 6,
        /// <summary>
        ///连接异常	
        /// </summary>
        [pbr::OriginalName("CONNECTERROR")] Connecterror = 7,
        /// <summary>
        ///版本过低
        /// </summary>
        [pbr::OriginalName("VERSIONOLD")] Versionold = 8,
        /// <summary>
        ///游客分配失败
        /// </summary>
        [pbr::OriginalName("NOMOREGUEST")] Nomoreguest = 9,
        /// <summary>
        ///所在ip登录过多
        /// </summary>
        [pbr::OriginalName("FREQUENTLY")] Frequently = 10,
        /// <summary>
        ///系统初始化，请稍后再试
        /// </summary>
        [pbr::OriginalName("APPINITING")] Appiniting = 11,
        /// <summary>
        ///服务端出错
        /// </summary>
        [pbr::OriginalName("SERVERERROR")] Servererror = 255,
        /// <summary>
        ///未知错误
        /// </summary>
        [pbr::OriginalName("UNKOWN")] Unkown = 1000,
        /// <summary>
        ///Token出错
        /// </summary>
        [pbr::OriginalName("TOKEN_FAILED")] TokenFailed = 1001,
        /// <summary>
        ///token过期了
        /// </summary>
        [pbr::OriginalName("TOKEN_EXPIRED")] TokenExpired = 1002,
        /// <summary>
        ///token与appid不匹配
        /// </summary>
        [pbr::OriginalName("TOKEN_NOTMATCH")] TokenNotmatch = 1003,
      }

    }
    #endregion

  }

  /// <summary>
  /// 注销登录
  /// </summary>
  public sealed partial class LogoutReq : pb::IMessage<LogoutReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogoutReq> _parser = new pb::MessageParser<LogoutReq>(() => new LogoutReq());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogoutReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutReq(LogoutReq other) : this() {
      _hasBits0 = other._hasBits0;
      userId_ = other.userId_;
      gateConnId_ = other.gateConnId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutReq Clone() {
      return new LogoutReq(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private readonly static ulong UserIdDefaultValue = 0UL;

    private ulong userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserId {
      get { if ((_hasBits0 & 1) != 0) { return userId_; } else { return UserIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        userId_ = value;
      }
    }
    /// <summary>Gets whether the "user_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUserId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "user_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUserId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "GateConnId" field.</summary>
    public const int GateConnIdFieldNumber = 2;
    private readonly static ulong GateConnIdDefaultValue = 0UL;

    private ulong gateConnId_;
    /// <summary>
    ///客户端可不填
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong GateConnId {
      get { if ((_hasBits0 & 2) != 0) { return gateConnId_; } else { return GateConnIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        gateConnId_ = value;
      }
    }
    /// <summary>Gets whether the "GateConnId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGateConnId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "GateConnId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGateConnId() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogoutReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogoutReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (GateConnId != other.GateConnId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUserId) hash ^= UserId.GetHashCode();
      if (HasGateConnId) hash ^= GateConnId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUserId) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (HasGateConnId) {
        output.WriteRawTag(16);
        output.WriteUInt64(GateConnId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUserId) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (HasGateConnId) {
        output.WriteRawTag(16);
        output.WriteUInt64(GateConnId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUserId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
      }
      if (HasGateConnId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GateConnId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogoutReq other) {
      if (other == null) {
        return;
      }
      if (other.HasUserId) {
        UserId = other.UserId;
      }
      if (other.HasGateConnId) {
        GateConnId = other.GateConnId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 16: {
            GateConnId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 16: {
            GateConnId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 注销登录
  /// </summary>
  public sealed partial class LogoutRsp : pb::IMessage<LogoutRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogoutRsp> _parser = new pb::MessageParser<LogoutRsp>(() => new LogoutRsp());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogoutRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutRsp(LogoutRsp other) : this() {
      _hasBits0 = other._hasBits0;
      reason_ = other.reason_;
      errInfo_ = other.errInfo_ != null ? other.errInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogoutRsp Clone() {
      return new LogoutRsp(this);
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private readonly static global::Bs.Lobby.LogoutRsp.Types.LogoutReason ReasonDefaultValue = global::Bs.Lobby.LogoutRsp.Types.LogoutReason.Normal;

    private global::Bs.Lobby.LogoutRsp.Types.LogoutReason reason_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Lobby.LogoutRsp.Types.LogoutReason Reason {
      get { if ((_hasBits0 & 1) != 0) { return reason_; } else { return ReasonDefaultValue; } }
      set {
        _hasBits0 |= 1;
        reason_ = value;
      }
    }
    /// <summary>Gets whether the "reason" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasReason {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "reason" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReason() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "err_info" field.</summary>
    public const int ErrInfoFieldNumber = 99;
    private global::Bs.Types.ErrorInfo errInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Types.ErrorInfo ErrInfo {
      get { return errInfo_; }
      set {
        errInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogoutRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogoutRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reason != other.Reason) return false;
      if (!object.Equals(ErrInfo, other.ErrInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasReason) hash ^= Reason.GetHashCode();
      if (errInfo_ != null) hash ^= ErrInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasReason) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasReason) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasReason) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (errInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ErrInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogoutRsp other) {
      if (other == null) {
        return;
      }
      if (other.HasReason) {
        Reason = other.Reason;
      }
      if (other.errInfo_ != null) {
        if (errInfo_ == null) {
          ErrInfo = new global::Bs.Types.ErrorInfo();
        }
        ErrInfo.MergeFrom(other.ErrInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = (global::Bs.Lobby.LogoutRsp.Types.LogoutReason) input.ReadEnum();
            break;
          }
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Reason = (global::Bs.Lobby.LogoutRsp.Types.LogoutReason) input.ReadEnum();
            break;
          }
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LogoutRsp message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum LogoutReason {
        [pbr::OriginalName("Normal")] Normal = 0,
        /// <summary>
        ///被顶号
        /// </summary>
        [pbr::OriginalName("AnotherLogin")] AnotherLogin = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// </summary>
  public sealed partial class LogicRegReq : pb::IMessage<LogicRegReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogicRegReq> _parser = new pb::MessageParser<LogicRegReq>(() => new LogicRegReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogicRegReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegReq(LogicRegReq other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegReq Clone() {
      return new LogicRegReq(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogicRegReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogicRegReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogicRegReq other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// </summary>
  public sealed partial class LogicRegRsp : pb::IMessage<LogicRegRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogicRegRsp> _parser = new pb::MessageParser<LogicRegRsp>(() => new LogicRegRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogicRegRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegRsp(LogicRegRsp other) : this() {
      errInfo_ = other.errInfo_ != null ? other.errInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogicRegRsp Clone() {
      return new LogicRegRsp(this);
    }

    /// <summary>Field number for the "err_info" field.</summary>
    public const int ErrInfoFieldNumber = 99;
    private global::Bs.Types.ErrorInfo errInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Types.ErrorInfo ErrInfo {
      get { return errInfo_; }
      set {
        errInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogicRegRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogicRegRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ErrInfo, other.ErrInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (errInfo_ != null) hash ^= ErrInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (errInfo_ != null) {
        output.WriteRawTag(154, 6);
        output.WriteMessage(ErrInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (errInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ErrInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogicRegRsp other) {
      if (other == null) {
        return;
      }
      if (other.errInfo_ != null) {
        if (errInfo_ == null) {
          ErrInfo = new global::Bs.Types.ErrorInfo();
        }
        ErrInfo.MergeFrom(other.ErrInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 794: {
            if (errInfo_ == null) {
              ErrInfo = new global::Bs.Types.ErrorInfo();
            }
            input.ReadMessage(ErrInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///用户状态
  /// </summary>
  public sealed partial class UserOnlineState : pb::IMessage<UserOnlineState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserOnlineState> _parser = new pb::MessageParser<UserOnlineState>(() => new UserOnlineState());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserOnlineState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bs.Lobby.LobbyReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserOnlineState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserOnlineState(UserOnlineState other) : this() {
      _hasBits0 = other._hasBits0;
      userInfo_ = other.userInfo_ != null ? other.userInfo_.Clone() : null;
      onlineState_ = other.onlineState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserOnlineState Clone() {
      return new UserOnlineState(this);
    }

    /// <summary>Field number for the "user_info" field.</summary>
    public const int UserInfoFieldNumber = 1;
    private global::Bs.Types.BaseUserInfo userInfo_;
    /// <summary>
    ///基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Types.BaseUserInfo UserInfo {
      get { return userInfo_; }
      set {
        userInfo_ = value;
      }
    }

    /// <summary>Field number for the "online_state" field.</summary>
    public const int OnlineStateFieldNumber = 2;
    private readonly static global::Bs.Lobby.UserOnlineState.Types.OnlineStat OnlineStateDefaultValue = global::Bs.Lobby.UserOnlineState.Types.OnlineStat.Online;

    private global::Bs.Lobby.UserOnlineState.Types.OnlineStat onlineState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bs.Lobby.UserOnlineState.Types.OnlineStat OnlineState {
      get { if ((_hasBits0 & 1) != 0) { return onlineState_; } else { return OnlineStateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        onlineState_ = value;
      }
    }
    /// <summary>Gets whether the "online_state" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOnlineState {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "online_state" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOnlineState() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserOnlineState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserOnlineState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserInfo, other.UserInfo)) return false;
      if (OnlineState != other.OnlineState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (userInfo_ != null) hash ^= UserInfo.GetHashCode();
      if (HasOnlineState) hash ^= OnlineState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (userInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserInfo);
      }
      if (HasOnlineState) {
        output.WriteRawTag(16);
        output.WriteEnum((int) OnlineState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (userInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserInfo);
      }
      if (HasOnlineState) {
        output.WriteRawTag(16);
        output.WriteEnum((int) OnlineState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (userInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserInfo);
      }
      if (HasOnlineState) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OnlineState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserOnlineState other) {
      if (other == null) {
        return;
      }
      if (other.userInfo_ != null) {
        if (userInfo_ == null) {
          UserInfo = new global::Bs.Types.BaseUserInfo();
        }
        UserInfo.MergeFrom(other.UserInfo);
      }
      if (other.HasOnlineState) {
        OnlineState = other.OnlineState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (userInfo_ == null) {
              UserInfo = new global::Bs.Types.BaseUserInfo();
            }
            input.ReadMessage(UserInfo);
            break;
          }
          case 16: {
            OnlineState = (global::Bs.Lobby.UserOnlineState.Types.OnlineStat) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (userInfo_ == null) {
              UserInfo = new global::Bs.Types.BaseUserInfo();
            }
            input.ReadMessage(UserInfo);
            break;
          }
          case 16: {
            OnlineState = (global::Bs.Lobby.UserOnlineState.Types.OnlineStat) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the UserOnlineState message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum OnlineStat {
        [pbr::OriginalName("Online")] Online = 1,
        [pbr::OriginalName("Disconnection")] Disconnection = 2,
        [pbr::OriginalName("Reconnect")] Reconnect = 3,
        [pbr::OriginalName("Offline")] Offline = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
